"use client";

import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "sonner";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" data-theme="emerald">
      <body className="font-inter">
        <Providers>
          {children}

          <Toaster richColors position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
